### ISSUE TITLE
Display letter object with template_id

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/amplify-front-end#19]
# Purpose: Use Lob to retrieve html that is displayed for the letter once representative is selected
<img width="561" alt="Screen Shot 2021-05-22 at 6 52 09 PM" src="https://user-images.githubusercontent.com/9143339/119246222-9c4e4200-bb34-11eb-8e9c-85064b1a49f2.png">

### 2. Call backend for _template_id_ (hardcode this variable until backend gives you variable:)
<img width="1358" alt="Screen Shot 2021-05-22 at 7 29 48 PM" src="https://user-images.githubusercontent.com/9143339/119246214-880a4500-bb34-11eb-9128-be765fd0d7f6.png">

### 3. Use GET Function from lob to retrieve the template object via **template_id**, use html attribute to display current letter [Docs](https://docs.lob.com/node#letters_create)
<img width="727" alt="Screen Shot 2021-05-22 at 7 25 20 PM" src="https://user-images.githubusercontent.com/9143339/119246272-21395b80-bb35-11eb-81bf-16f67c75cb95.png">

**Comment by manishapriya94** [comment]
Hi @BeeXiong, it seems backend needs the following for timeout issues? 
We have the get request in a try catch, but the request itself after the .then()should have .catch(err => res.send(err))

**Comment by hamdaankhalid** [comment]
@manishapriya94 @BeeXiong 
After a bit of looking around on similar errors in axios, turns out there seems to be a pattern that some errors in the axis request do not get caught in the catch block, and need to have  the catch chained to catch correctly. Not 100% sure why this happens but it results in a timeout exception on the client as no response is sent back, my hypothesis is that this is the case in our situation too! an uncaught exception that blocks the response.

**Comment by manishapriya94** [comment]
@mscoutermarsh have you dealt with this before?

**Comment by mahrsbar** [comment]
Thanks @hamdaankhalid! Are you able to push your current front-end changes so I can replicate this issue and attempt to debug? If you could create a pull request for your branch, that'd be awesome!

**Comment by hamdaankhalid** [comment]
@mahrsbar I'll push it tomorrow morning 👍🏽 (Eastern Time)

**Comment by hamdaankhalid** [comment]
@mahrsbar https://github.com/Ally-Guide/amplify-front-end/pull/33
